"""
Widget contract definitions and adapters.

ABC-based widget contracts that eliminate duck typing in favor of
explicit, fail-loud inheritance-based architecture.
"""

from .codegen_provider import (
    CodegenProviderABC,
    get_codegen_provider,
    register_codegen_provider,
)
from .component_selection import (
    ComponentSelectionProviderABC,
    FunctionSelectionProviderABC,
    get_component_selection_provider,
    get_function_selection_provider,
    register_component_selection_provider,
    register_function_selection_provider,
)
from .form_config import FormGenConfig, get_form_config, set_form_config
from .log_providers import (
    LogDiscoveryProviderABC,
    ServerScanProviderABC,
    get_log_discovery_provider,
    get_server_scan_provider,
    register_log_discovery_provider,
    register_server_scan_provider,
)
from .preview_formatter import PreviewFormatterRegistry, register_preview_formatter
from .widget_adapters import (
    CheckBoxAdapter,
    ComboBoxAdapter,
    DoubleSpinBoxAdapter,
    KeySequenceEditAdapter,
    LineEditAdapter,
    PlaceholderStateMixin,
    PyQtWidgetMeta,
    SpinBoxAdapter,
)
from .widget_protocols import (
    ChangeSignalEmitter,
    ChildFieldChromeRefreshable,
    ChildFieldIdentityProvider,
    ChildFieldNavigationTargetProvider,
    ChildFieldSemanticChromeRefreshable,
    ChildSubfieldNavigationTargetProvider,
    CurrentValueValidatable,
    DirtyMarkerSettable,
    EnumSelectable,
    InlineDataclassGroupBoxChromeProvider,
    InlineDataclassRootResettable,
    PlaceholderCapable,
    PlaceholderStateTrackable,
    RangeConfigurable,
    RawResolvedValueSettable,
    ResolvedValuePreviewSettable,
    ValueGettable,
    ValueSettable,
    WidgetCapability,
    WidgetCapabilityTagged,
    widget_capability_tags,
    widget_supports_capability,
)

__all__ = [
    "ValueGettable",
    "ValueSettable",
    "CurrentValueValidatable",
    "DirtyMarkerSettable",
    "ResolvedValuePreviewSettable",
    "RawResolvedValueSettable",
    "ChildFieldChromeRefreshable",
    "ChildFieldSemanticChromeRefreshable",
    "ChildFieldIdentityProvider",
    "ChildFieldNavigationTargetProvider",
    "ChildSubfieldNavigationTargetProvider",
    "InlineDataclassGroupBoxChromeProvider",
    "InlineDataclassRootResettable",
    "PlaceholderCapable",
    "PlaceholderStateTrackable",
    "WidgetCapability",
    "WidgetCapabilityTagged",
    "widget_capability_tags",
    "widget_supports_capability",
    "RangeConfigurable",
    "EnumSelectable",
    "ChangeSignalEmitter",
    "LineEditAdapter",
    "KeySequenceEditAdapter",
    "SpinBoxAdapter",
    "DoubleSpinBoxAdapter",
    "ComboBoxAdapter",
    "CheckBoxAdapter",
    "PlaceholderStateMixin",
    "PyQtWidgetMeta",
    "PreviewFormatterRegistry",
    "register_preview_formatter",
    "FormGenConfig",
    "set_form_config",
    "get_form_config",
    "CodegenProviderABC",
    "register_codegen_provider",
    "get_codegen_provider",
    "LogDiscoveryProviderABC",
    "ServerScanProviderABC",
    "register_log_discovery_provider",
    "get_log_discovery_provider",
    "register_server_scan_provider",
    "get_server_scan_provider",
    "ComponentSelectionProviderABC",
    "FunctionSelectionProviderABC",
    "register_component_selection_provider",
    "get_component_selection_provider",
    "register_function_selection_provider",
    "get_function_selection_provider",
]
